// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(options, imports, register) {
    var callback, content, msgs, storage;
    msgs = imports.messages;
    storage = imports.storage;
    if (!((msgs != null) && (storage != null))) {
      return;
    }
    content = {};
    callback = function(context, data, caller) {
      var error_cb;
      if (!caller.isOwner) {
        console.log("invalid caller for modifying                 the texteditor for " + context);
        return;
      }
      content[context] = data;
      error_cb = function(error, timestamp) {
        if (error != null) {
          console.log("error storing texteditor: " + error);
        }
        return msgs.broadcast('texteditor', context, data, caller);
      };
      return storage.add('texteditor', context, data, error_cb);
    };
    return msgs.listen('texteditor', callback);
  };

}).call(this);
